/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    Badge: typeof import('./../src/components/badge.vue')['default']
    CustomSwiper: typeof import('./../src/components/custom-swiper.vue')['default']
    GuessLike: typeof import('./../src/components/guess-like.vue')['default']
    HomeCategoryPanel: typeof import('./../src/components/home/home-category-panel.vue')['default']
    HomeHotPanel: typeof import('./../src/components/home/home-hot-panel.vue')['default']
    HomeNavbar: typeof import('./../src/components/home/home-navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
